sentry_decision_node:
  ros__parameters:
    # 双阈值血量控制（防止血量在阈值附近来回横跳）
    # 血量低于 hp_threshold_low 触发回家补血；补血后需超过 hp_threshold_high 才回X作战
    hp_threshold_low: 150    # 低血量阈值：低于此值去Y补血（例：总血量600，低于200触发撤退）
    hp_threshold_high: 380  # 高血量阈值：补血后超过此值才回X（防止补一点血就立刻回去被打）
    
    # 机器人状态话题
    robot_status_topic: "/robot_status"
    
    # 裁判系统数据话题
    gimbal_data_topic: "/gimbal_data"
    
    # 检查间隔（秒）
    check_interval: 1.0

    # 朝向漂移容忍阈值（rad），到达目标点后若实际朝向与目标朝向差超过此值则重新导航修正
    # 0.3 rad ≈ 17°，可根据实际场地需求调整
    yaw_drift_tolerance: 0.8
    
    # 目标点X [x, y, yaw] (血量健康时前往)
    # 地图坐标，示例：斨场某个防守点
    

    target_x: [2.9,5.0,3.12]
    #target_x: [-0.4,0.5,1.57]
    #target_x: [0.0,0.9,0.0]
    # 目标点Y [x, y, yaw] (血量低时前往)
    # 地图坐标，示例：补弹区或安全区
    
    target_y: [0.0,0.0,0.1]
    # 去往目标点X的途径点 [x1, y1, yaw1, x2, y2, yaw2, ...]
    # 必须是3的倍数，每3个数值代表一个途径点 (x, y, yaw)
    #waypoints_to_x: [0.0,0.0,1.57]
    # waypoints_to_x: [4.14,0.529,0.0,4.68,-3.64,-0.0,1.19,-4.12,1.57]
    waypoints_to_x: [
     1.0,0.0,0.0,2.0,0.0,0.0 ,3.0,0.0,0.0,4.0,0.0,0.0,5.0,0.0,1.0,5.0,1.0,1.57,
     5.0 ,2.0, 1.57,5.0 ,3.0, 1.57,5.0,4.0, 1.57,5.0,5.0, 1.57,4.0,5.0,3.12,3.0,5.0,3.12 ]
 
    # 去往目标点Y的途径点 [x1, y1, yaw1, x2, y2, yaw2, ...]
    # 必须是3的倍数，每3个数值代表一个途径点 (x, y, yaw)
    waypoints_to_y: [
     4.0,5.0,0.0, 5.0,5.0, 0.0, 5.0,4.0, -1.57,
     5.0 ,3.0, -1.57,5.0 ,2.0, -1.57,5.0,1.0,-1.57,5.0,0.0,-1.57,4.0,0.0,3.1,3.0,0.0,3.1
     ]
    waypoints_to_y: [-0.5,-0.2,0.0]
    
