<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sentry_bringup</name>
  <version>0.1.0</version>
  <description>Single entry point for the sentry robot system.</description>
  <maintainer email="gzu-prink@example.com">gzu-prink</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>sentry_hardware</exec_depend>
  <exec_depend>sentry_description</exec_depend>
  <exec_depend>sentry_localization</exec_depend>
  <exec_depend>sentry_perception</exec_depend>
  <exec_depend>pb2025_nav_bringup</exec_depend>
  <exec_depend>pointcloud_to_laserscan</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
