simple_nav_node:
  ros__parameters:
    # 地图坐标系
    map_frame: "map"

    # 是否循环巡逻（到达最后一个目标点后重新开始）
    loop_patrol: false

    # 到达目标点后等待时间（秒）
    wait_at_goal: 1.0
    # 目标点列表，格式：[x1, y1, yaw1, x2, y2, yaw2, ...]
    # yaw单位为弧度，0=朝东，1.57=朝北，3.14=朝西，-1.57=朝南
    # 机器人会依次经过所有目标点，然后循环
    goals: [
      # 0.0,  0.0,  0.-0,   
      # 0.0,  0.0,  0.0,
      # 0.0,  0.0,  0.0, # 目标点1：(1.0, 0.0)，朝东
      -1.78,-3.76, 0.1,   # 目标点2：(2.0, 1.0)，朝北  
      9.52, -7.112, 3.14,  # 目标点3：(0.0, 2.0)，朝西
      5.0556, -2.074,   0.1,
      5.0556, -2.074,   0.1
      # e0.256, -0.9,   0.1   # 目标点4：回到原点
    ]
